### ISSUE TITLE
Invalid assignment error

### ISSUE THREAD

**Issue by niksmac** [manuel-di-iorio/promisify-es6#2]
```
Failed to compile.

static/js/main.d834a8b4.js from UglifyJs
Invalid assignment [./~/promisify-es6/index.js:26,0][static/js/main.d834a8b4.js:2961,41]


npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/niksair/.nvm/versions/node/v7.8.0/bin/node" "/Users/niksair/.nvm/versions/node/v7.8.0/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Is this package specific?

**Comment by manuel-di-iorio** [comment]
Thanks for reporting! 

Looks like the version of uglifyJS you are using does not support javascript ES6 syntax, which is only supported starting from the new harmony v3 (https://github.com/mishoo/UglifyJS2/issues/448). Also, `promisify-es6` is currently not supported when used client-side (because of the Node.js code).

I'm about to commit a client-side es5 version of `promisify-es6` that will address this issue.

**Comment by niksmac** [comment]
I am actually using the `harmony` branch 
` "uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony",`

**Comment by manuel-di-iorio** [comment]
I updated the package with the support for es5/client-side and minification (tested with uglifyJS).
I also included an already minified file _(index.min.js)_, if may help.
Let me know if the issue still persists

**Comment by niksmac** [comment]
Looking good [3fb20250c33](https://github.com/manuel-di-iorio/promisify-es6/tree/3fb20250c33)
